CREATE DATABASE IF NOT EXISTS taskflow_db CHARACTER SET utf8mb4 COLLATE
utf8mb4_unicode_ci;

USE taskflow_db;

CREATE TABLE usuarios ( id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nome
VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, senha_hash
VARCHAR(255), criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP )
ENGINE=InnoDB;

CREATE TABLE tarefas ( id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
usuario_id INT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL,
descricao TEXT NULL, status
ENUM('PENDENTE','EM_ANDAMENTO','CONCLUIDA','CANCELADA') NOT NULL DEFAULT
'PENDENTE', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
concluido_em DATETIME NULL, FOREIGN KEY (usuario_id) REFERENCES
usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB;

CREATE INDEX performanceusuario ON tarefas (usuario_id); CREATE UNIQUE
INDEX perfomancestatus ON tarefas (usuario_id, status); CREATE INDEX
performancecriado_em ON tarefas (criado_em);
